# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69275138cf39081ece4ba96a777bfc4c1eeb07fad9e8398a4f118a801fa84f0cf9b2901e6a2f5c5bf8cc5145c45dab1f5cfb7601e45af14e6032a5577586682

test:
  secret_key_base: e0d0f34c8e8cb702cacc83bac51c5a683a796d583addb91c155ada6e40f1e4e804236582871c3a633accd788b4cc9afa62ed7ba2bc19059668669eea7adc8812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
